DROP TABLE MOOLMORTHS.ORDER_PRODUCT;
DROP TABLE MOOLMORTHS.ORDER;
DROP TABLE MOOLMORTHS.DELIVERY_DETAILS;
DROP TABLE MOOLMORTHS.PRODUCT;
DROP TABLE MOOLMORTHS.SUBCATEGORY;
DROP TABLE MOOLMORTHS.CATEGORY;