CREATE TABLE MOOLMORTHS.ORDER (
  ID int NOT NULL AUTO_INCREMENT,
  DELIVERY_DETAILS_ID int NOT NULL,
  CREATED_AT datetime NOT NULL,
  TOTAL_QUANTITY int NOT NULL,
  TOTAL_PRICE float NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (DELIVERY_DETAILS_ID) REFERENCES MOOLMORTHS.DELIVERY_DETAILS(ID)
);
