CREATE TABLE MOOLMORTHS.ORDER_PRODUCT (
  ORDER_ID int NOT NULL,
  PRODUCT_ID int NOT NULL,
  QUANTITY int NOT NULL,
  PRIMARY KEY (ORDER_ID, PRODUCT_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES MOOLMORTHS.ORDER (ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES MOOLMORTHS.PRODUCT (ID)
);
